export type ThemeColors = {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  success: string;
  warning: string;
  xp: string;
  gold: string;
  rank: string;
  surface: string;
  tint: string;
  text: string;
};

export type ThemeDefinition = {
  id: string;
  name: string;
  colors: ThemeColors;
};

export const THEMES: Record<string, ThemeDefinition> = {
  obsidian: {
    id: "obsidian",
    name: "Obsidian Neon",
    colors: {
      background: "#050505",
      foreground: "#FAFAFA",
      card: "#121217",
      cardForeground: "#FAFAFA",
      primary: "#00E5FF",
      primaryForeground: "#050505",
      secondary: "#0D0D12",
      secondaryForeground: "#C0C0D0",
      muted: "#0D0D12",
      mutedForeground: "#8A8A9E",
      accent: "#B026FF",
      accentForeground: "#FAFAFA",
      destructive: "#FF2A6D",
      destructiveForeground: "#ffffff",
      border: "#222228",
      input: "#222228",
      success: "#00FA9A",
      warning: "#FFEA00",
      xp: "#B026FF",
      gold: "#FFD700",
      rank: "#FFD700",
      surface: "#181820",
      tint: "#00E5FF",
      text: "#FAFAFA",
    },
  },
  midnight: {
    id: "midnight",
    name: "Midnight Pulse",
    colors: {
      background: "#0A0A12",
      foreground: "#ECECF0",
      card: "#181825",
      cardForeground: "#ECECF0",
      primary: "#B026FF",
      primaryForeground: "#FFFFFF",
      secondary: "#1A1A24",
      secondaryForeground: "#A0A0B0",
      muted: "#1A1A24",
      mutedForeground: "#606070",
      accent: "#FF00FF",
      accentForeground: "#FFFFFF",
      destructive: "#FF4D4D",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A3A",
      input: "#2A2A3A",
      success: "#50FA7B",
      warning: "#F1FA8C",
      xp: "#BD93F9",
      gold: "#FFB86C",
      rank: "#FFB86C",
      surface: "#282A36",
      tint: "#BD93F9",
      text: "#F8F8F2",
    },
  },
  emerald: {
    id: "emerald",
    name: "Emerald Oasis",
    colors: {
      background: "#050805",
      foreground: "#F0FFF4",
      card: "#0D120D",
      cardForeground: "#F0FFF4",
      primary: "#00FF9D",
      primaryForeground: "#050805",
      secondary: "#141C14",
      secondaryForeground: "#A0B0A0",
      muted: "#141C14",
      mutedForeground: "#607060",
      accent: "#D4FF00",
      accentForeground: "#050805",
      destructive: "#FF3E3E",
      destructiveForeground: "#FFFFFF",
      border: "#1D281D",
      input: "#1D281D",
      success: "#00FF9D",
      warning: "#FFF000",
      xp: "#00FF9D",
      gold: "#FFD700",
      rank: "#FFD700",
      surface: "#1A251A",
      tint: "#00FF9D",
      text: "#F0FFF4",
    },
  },
  crystal: {
    id: "crystal",
    name: "Crystal Loft",
    colors: {
      background: "#F4F7FA",
      foreground: "#0B1528",
      card: "#FFFFFF",
      cardForeground: "#0B1528",
      primary: "#0A65FF",
      primaryForeground: "#FFFFFF",
      secondary: "#EAEFF5",
      secondaryForeground: "#586A82",
      muted: "#EAEFF5",
      mutedForeground: "#8BA0B8",
      accent: "#9D4EDD",
      accentForeground: "#FFFFFF",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#DDE4EE",
      input: "#FFFFFF",
      success: "#34C759",
      warning: "#FF9500",
      xp: "#0A65FF",
      gold: "#F5A623",
      rank: "#F5A623",
      surface: "#FFFFFF",
      tint: "#0A65FF",
      text: "#1E2A3B",
    },
  },
  rosegold: {
    id: "rosegold",
    name: "Rose Gold",
    colors: {
      background: "#FFF5F5",
      foreground: "#5C2D2D",
      card: "#FFFFFF",
      cardForeground: "#5C2D2D",
      primary: "#D97B7B",
      primaryForeground: "#FFFFFF",
      secondary: "#FFE4E4",
      secondaryForeground: "#8E5C5C",
      muted: "#FFE4E4",
      mutedForeground: "#B68B8B",
      accent: "#FFBABA",
      accentForeground: "#5C2D2D",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#F5DADA",
      input: "#FFFFFF",
      success: "#D97B7B",
      warning: "#FFCC00",
      xp: "#D97B7B",
      gold: "#D4AF37",
      rank: "#D4AF37",
      surface: "#FFFFFF",
      tint: "#D97B7B",
      text: "#5C2D2D",
    },
  },
  sunset: {
    id: "sunset",
    name: "Sunset Ember",
    colors: {
      background: "#0D0502",
      foreground: "#FFF5F0",
      card: "#1A0905",
      cardForeground: "#FFF5F0",
      primary: "#FF6B35",
      primaryForeground: "#0D0502",
      secondary: "#2D0F08",
      secondaryForeground: "#D9A596",
      muted: "#2D0F08",
      mutedForeground: "#8C6A60",
      accent: "#F7B733",
      accentForeground: "#0D0502",
      destructive: "#FF3E3E",
      destructiveForeground: "#FFFFFF",
      border: "#3D140B",
      input: "#3D140B",
      success: "#FF6B35",
      warning: "#F7B733",
      xp: "#FF6B35",
      gold: "#F7B733",
      rank: "#F7B733",
      surface: "#250D07",
      tint: "#FF6B35",
      text: "#FFF5F0",
    },
  },
  midnightpro: {
    id: "midnightpro",
    name: "Midnight Pro",
    colors: {
      background: "#000000",
      foreground: "#FFFFFF",
      card: "#0A0A0A",
      cardForeground: "#FFFFFF",
      primary: "#007AFF",
      primaryForeground: "#FFFFFF",
      secondary: "#1C1C1E",
      secondaryForeground: "#8E8E93",
      muted: "#1C1C1E",
      mutedForeground: "#636366",
      accent: "#5856D6",
      accentForeground: "#FFFFFF",
      destructive: "#FF453A",
      destructiveForeground: "#FFFFFF",
      border: "#2C2C2E",
      input: "#1C1C1E",
      success: "#32D74B",
      warning: "#FFD60A",
      xp: "#0A84FF",
      gold: "#FFD60A",
      rank: "#FFD60A",
      surface: "#0A0A0A",
      tint: "#0A84FF",
      text: "#FFFFFF",
    },
  },
  galaxy: {
    id: "galaxy",
    name: "Galaxy Nebula",
    colors: {
      background: "#0D0D2B",
      foreground: "#E0E0FF",
      card: "#1A1A3F",
      cardForeground: "#E0E0FF",
      primary: "#8A2BE2",
      primaryForeground: "#FFFFFF",
      secondary: "#2B2B5A",
      secondaryForeground: "#C0C0E0",
      muted: "#2B2B5A",
      mutedForeground: "#8080A0",
      accent: "#FF00FF",
      accentForeground: "#FFFFFF",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#3A3A6F",
      input: "#1A1A3F",
      success: "#00FF9D",
      warning: "#FFEA00",
      xp: "#8A2BE2",
      gold: "#FFD700",
      rank: "#FFD700",
      surface: "#0D0D2B",
      tint: "#8A2BE2",
      text: "#E0E0FF",
    },
  },
  aurora: {
    id: "aurora",
    name: "Aurora Dawn",
    colors: {
      background: "#FFF5E6",
      foreground: "#2B1B0C",
      card: "#FFEED9",
      cardForeground: "#2B1B0C",
      primary: "#FF7F50",
      primaryForeground: "#2B1B0C",
      secondary: "#FFDAB9",
      secondaryForeground: "#8B5A2B",
      muted: "#FFE4C4",
      mutedForeground: "#A0522D",
      accent: "#FF4500",
      accentForeground: "#FFFFFF",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#D2B48C",
      input: "#FFF5E6",
      success: "#32CD32",
      warning: "#FFA500",
      xp: "#FF7F50",
      gold: "#FFD700",
      rank: "#FFD700",
      surface: "#FFF5E6",
      tint: "#FF7F50",
      text: "#2B1B0C",
    },
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk 2077",
    colors: {
      background: "#0F0F0F",
      foreground: "#FCEE09",
      card: "#1A1A1A",
      cardForeground: "#FCEE09",
      primary: "#FCEE09", // Iconic Yellow
      primaryForeground: "#0F0F0F",
      secondary: "#00E5FF", // Cyan secondary
      secondaryForeground: "#0F0F0F",
      muted: "#222222",
      mutedForeground: "#888888",
      accent: "#FF003C", // Vivid Red accent
      accentForeground: "#FFFFFF",
      destructive: "#FF003C",
      destructiveForeground: "#FFFFFF",
      border: "#FCEE0933",
      input: "#1A1A1A",
      success: "#00E5FF",
      warning: "#FCEE09",
      xp: "#FCEE09",
      gold: "#FCEE09",
      rank: "#FCEE09",
      surface: "#1A1A1A",
      tint: "#FCEE09",
      text: "#FCEE09",
    },
  },
  deepsea: {
    id: "deepsea",
    name: "Deep Sea",
    colors: {
      background: "#001219",
      foreground: "#94D2BD",
      card: "#001E29",
      cardForeground: "#94D2BD",
      primary: "#0A9396",
      primaryForeground: "#E9D8A6",
      secondary: "#005F73",
      secondaryForeground: "#94D2BD",
      muted: "#002B36",
      mutedForeground: "#588157",
      accent: "#EE9B00",
      accentForeground: "#001219",
      destructive: "#AE2012",
      destructiveForeground: "#FFFFFF",
      border: "#005F7344",
      input: "#001E29",
      success: "#94D2BD",
      warning: "#E9D8A6",
      xp: "#0A9396",
      gold: "#EE9B00",
      rank: "#EE9B00",
      surface: "#001219",
      tint: "#0A9396",
      text: "#CA6702",
    },
  },
  royalvelvet: {
    id: "royalvelvet",
    name: "Royal Velvet",
    colors: {
      background: "#1A0033",
      foreground: "#FFD700",
      card: "#2D0052",
      cardForeground: "#FFD700",
      primary: "#FFD700", // Gold
      primaryForeground: "#1A0033",
      secondary: "#4B0082",
      secondaryForeground: "#FFD700",
      muted: "#240046",
      mutedForeground: "#9D4EDD",
      accent: "#7B2CBF",
      accentForeground: "#FFFFFF",
      destructive: "#FF4500",
      destructiveForeground: "#FFFFFF",
      border: "#FFD70033",
      input: "#2D0052",
      success: "#FFD700",
      warning: "#FFD700",
      xp: "#FFD700",
      gold: "#FFD700",
      rank: "#FFD700",
      surface: "#1A0033",
      tint: "#FFD700",
      text: "#FFD700",
    },
  },
  titanium: {
    id: "titanium",
    name: "Titanium Elite",
    colors: {
      background: "#000000",
      foreground: "#E5E4E2",
      card: "#0F0F10",
      cardForeground: "#FFFFFF",
      primary: "#FFFFFF",
      primaryForeground: "#000000",
      secondary: "#1C1C1E",
      secondaryForeground: "#A0A0A5",
      muted: "#111112",
      mutedForeground: "#707075",
      accent: "#D1D1D6",
      accentForeground: "#000000",
      destructive: "#FF453A",
      destructiveForeground: "#FFFFFF",
      border: "#2C2C2E",
      input: "#1C1C1E",
      success: "#32D74B",
      warning: "#FFD60A",
      xp: "#E5E4E2",
      gold: "#FFD700",
      rank: "#E5E4E2",
      surface: "#0A0A0B",
      tint: "#FFFFFF",
      text: "#E5E4E2",
    },
  },
  phantom: {
    id: "phantom",
    name: "Phantom Neon",
    colors: {
      background: "#05010A",
      foreground: "#F0F0FF",
      card: "#0D0512",
      cardForeground: "#FFFFFF",
      primary: "#00F5FF",
      primaryForeground: "#05010A",
      secondary: "#1A0A25",
      secondaryForeground: "#9D4EDD",
      muted: "#12051A",
      mutedForeground: "#5A189A",
      accent: "#FF00FF",
      accentForeground: "#FFFFFF",
      destructive: "#FF2D55",
      destructiveForeground: "#FFFFFF",
      border: "#3C096C44",
      input: "#10002B",
      success: "#00F5FF",
      warning: "#FF9100",
      xp: "#9D4EDD",
      gold: "#FFD700",
      rank: "#00F5FF",
      surface: "#05010A",
      tint: "#00F5FF",
      text: "#E0AAFF",
    },
  },
  liquidglass: {
    id: "liquidglass",
    name: "Liquid Glass",
    colors: {
      background: "#F0F2F5",
      foreground: "#1D1D1F",
      card: "#FFFFFF",
      cardForeground: "#1D1D1F",
      primary: "#007AFF",
      primaryForeground: "#FFFFFF",
      secondary: "#E8EAED",
      secondaryForeground: "#5F6368",
      muted: "#F1F3F4",
      mutedForeground: "#9AA0A6",
      accent: "#5856D6",
      accentForeground: "#FFFFFF",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#DADCE0",
      input: "#FFFFFF",
      success: "#34C759",
      warning: "#FF9500",
      xp: "#5856D6",
      gold: "#FBBC04",
      rank: "#FBBC04",
      surface: "#FFFFFF",
      tint: "#007AFF",
      text: "#202124",
    },
  },
};
