const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#0D0D1A",
    foreground: "#F0F0FF",
    card: "#16162A",
    cardForeground: "#F0F0FF",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#1E1E35",
    secondaryForeground: "#C4C4E0",
    muted: "#1E1E35",
    mutedForeground: "#7070A0",
    accent: "#06B6D4",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A45",
    input: "#2A2A45",
    success: "#22D3EE",
    warning: "#F59E0B",
    xp: "#A78BFA",
  },
  dark: {
    text: "#F0F0FF",
    tint: "#A78BFA",
    background: "#0D0D1A",
    foreground: "#F0F0FF",
    card: "#16162A",
    cardForeground: "#F0F0FF",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#1E1E35",
    secondaryForeground: "#C4C4E0",
    muted: "#1E1E35",
    mutedForeground: "#7070A0",
    accent: "#06B6D4",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A45",
    input: "#2A2A45",
    success: "#22D3EE",
    warning: "#F59E0B",
    xp: "#A78BFA",
  },
  radius: 16,
};

export default colors;
